language: python

python:
  - "3.6"

install:
  - pip install -r requirements_testing.txt
  - pip install coverage
  - pip install coveralls

script:
  - coverage run manage.py test

after_success:
  coveralls
